use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::BTreeMap;
use utoipa::{IntoParams, ToSchema};

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "code": "resource_not_found",
    "message": "tenant 'tenant-0001' was not found",
    "request_id": "req-20260409-0001",
    "details": {
        "resource": "tenant",
        "id": "tenant-0001"
    }
}))]
pub struct PlatformApiError {
    /// Stable machine-readable error code.
    #[schema(example = "resource_not_found")]
    pub code: String,
    /// Human-readable error safe to display to operators.
    #[schema(example = "tenant 'tenant-0001' was not found")]
    pub message: String,
    /// Optional request identifier propagated by the platform.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "req-20260409-0001")]
    pub request_id: Option<String>,
    /// Optional machine-readable context for callers and audits.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<BTreeMap<String, String>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "status": "ok",
    "service": "aria-controller",
    "version": "0.1.0",
    "resource_kinds": {
        "tenants": 1,
        "nodes": 2,
        "networks": 3,
        "ports": 12,
        "security_groups": 4,
        "route_tables": 3
    }
}))]
pub struct ControllerHealthResponse {
    /// Overall controller health.
    #[schema(example = "ok")]
    pub status: String,
    /// Service name reporting the status.
    #[schema(example = "aria-controller")]
    pub service: String,
    /// Controller version string.
    #[schema(example = "0.1.0")]
    pub version: String,
    /// Current in-memory object counts by resource kind.
    pub resource_kinds: BTreeMap<String, usize>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "id": "tenant-0001",
    "resource_version": "3",
    "created_at": "1712649600",
    "updated_at": "1712649655",
    "labels": {
        "env": "prod"
    }
}))]
pub struct ResourceMetadata {
    /// Stable resource identifier.
    #[schema(example = "tenant-0001")]
    pub id: String,
    /// Monotonic resource version used for audit and optimistic workflows.
    #[schema(example = "3")]
    pub resource_version: String,
    /// Creation timestamp string generated by the controller.
    #[schema(example = "1712649600")]
    pub created_at: String,
    /// Last update timestamp string generated by the controller.
    #[schema(example = "1712649655")]
    pub updated_at: String,
    /// Free-form labels attached to the resource.
    #[serde(default)]
    pub labels: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "id": "tenant-0001",
    "labels": {
        "env": "prod"
    }
}))]
pub struct ResourceCreateMetadata {
    /// Optional caller-provided identifier. When omitted the controller allocates one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "tenant-0001")]
    pub id: Option<String>,
    /// Optional labels to attach on creation.
    #[serde(default)]
    pub labels: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "resource_version": "3",
    "labels": {
        "env": "staging"
    }
}))]
pub struct ResourceUpdateMetadata {
    /// Optional last-seen resource version supplied by the caller.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "3")]
    pub resource_version: Option<String>,
    /// Optional full replacement label set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, IntoParams, ToSchema)]
#[into_params(parameter_in = Query)]
pub struct TenantListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = 50, minimum = 1, maximum = 200)]
    pub limit: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "50")]
    pub page_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "env=prod")]
    pub label_selector: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "ready")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, IntoParams, ToSchema)]
#[into_params(parameter_in = Query)]
pub struct NodeListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = 50, minimum = 1, maximum = 200)]
    pub limit: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "50")]
    pub page_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "rack=r1")]
    pub label_selector: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "registered")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, IntoParams, ToSchema)]
#[into_params(parameter_in = Query)]
pub struct NetworkListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = 50, minimum = 1, maximum = 200)]
    pub limit: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "50")]
    pub page_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "tier=prod")]
    pub label_selector: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "tenant-0001")]
    pub tenant_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "ready")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, IntoParams, ToSchema)]
#[into_params(parameter_in = Query)]
pub struct PortListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = 50, minimum = 1, maximum = 200)]
    pub limit: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "50")]
    pub page_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "role=frontend")]
    pub label_selector: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "tenant-0001")]
    pub tenant_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "network-0001")]
    pub network_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "node-0001")]
    pub node_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "pending")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, IntoParams, ToSchema)]
#[into_params(parameter_in = Query)]
pub struct SecurityGroupListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = 50, minimum = 1, maximum = 200)]
    pub limit: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "50")]
    pub page_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "tier=frontend")]
    pub label_selector: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "tenant-0001")]
    pub tenant_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "ready")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize, IntoParams, ToSchema)]
#[into_params(parameter_in = Query)]
pub struct RouteTableListQuery {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = 50, minimum = 1, maximum = 200)]
    pub limit: Option<usize>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "50")]
    pub page_token: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "scope=prod")]
    pub label_selector: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "network-0001")]
    pub network_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[param(example = "ready")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "name": "prod",
    "description": "Primary production tenant",
    "quotas": {
        "networks": 32,
        "ports": 2048
    }
}))]
pub struct TenantSpec {
    /// Human-readable tenant name.
    #[schema(example = "prod")]
    pub name: String,
    /// Optional tenant description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "Primary production tenant")]
    pub description: Option<String>,
    /// Optional quota hints enforced by higher-level control logic.
    #[serde(default)]
    pub quotas: BTreeMap<String, u64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "phase": "ready"
}))]
pub struct TenantStatus {
    /// Lifecycle phase as observed by the controller.
    #[schema(example = "ready")]
    pub phase: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "metadata": {
        "id": "tenant-0001",
        "resource_version": "3",
        "created_at": "1712649600",
        "updated_at": "1712649655",
        "labels": {"env": "prod"}
    },
    "spec": {
        "name": "prod",
        "description": "Primary production tenant",
        "quotas": {"networks": 32, "ports": 2048}
    },
    "status": {
        "phase": "ready"
    }
}))]
pub struct TenantResource {
    pub metadata: ResourceMetadata,
    pub spec: TenantSpec,
    pub status: TenantStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct CreateTenantRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceCreateMetadata>,
    pub spec: TenantSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct UpdateTenantRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceUpdateMetadata>,
    pub spec: TenantSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct TenantListResponse {
    pub items: Vec<TenantResource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    pub total_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "name": "node-sh-01",
    "mgmt_address": "10.10.0.11",
    "az": "cn-east-1a"
}))]
pub struct NodeSpec {
    /// Human-readable node name.
    #[schema(example = "node-sh-01")]
    pub name: String,
    /// Management address used for controller-to-agent coordination.
    #[schema(example = "10.10.0.11")]
    pub mgmt_address: String,
    /// Availability zone or fault domain label.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "cn-east-1a")]
    pub az: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "phase": "ready",
    "agent_version": "0.9.0",
    "kernel_version": "6.8.0-71-generic",
    "capabilities": ["xdp", "tc", "kernel_drops"]
}))]
pub struct NodeStatus {
    /// Lifecycle phase as reported by the platform.
    #[schema(example = "ready")]
    pub phase: String,
    /// Currently observed agent version.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "0.9.0")]
    pub agent_version: Option<String>,
    /// Observed kernel version.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "6.8.0-71-generic")]
    pub kernel_version: Option<String>,
    /// Datapath capabilities surfaced by the node.
    #[serde(default)]
    pub capabilities: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "metadata": {
        "id": "node-0001",
        "resource_version": "1",
        "created_at": "1712649600",
        "updated_at": "1712649600",
        "labels": {"rack": "r1"}
    },
    "spec": {
        "name": "node-sh-01",
        "mgmt_address": "10.10.0.11",
        "az": "cn-east-1a"
    },
    "status": {
        "phase": "ready",
        "agent_version": "0.9.0",
        "kernel_version": "6.8.0-71-generic",
        "capabilities": ["xdp", "tc"]
    }
}))]
pub struct NodeResource {
    pub metadata: ResourceMetadata,
    pub spec: NodeSpec,
    pub status: NodeStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct CreateNodeRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceCreateMetadata>,
    pub spec: NodeSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct UpdateNodeRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceUpdateMetadata>,
    pub spec: NodeSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct NodeListResponse {
    pub items: Vec<NodeResource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    pub total_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "tenant_id": "tenant-0001",
    "name": "prod-vpc",
    "network_type": "l3",
    "ipv4_enabled": true,
    "ipv6_enabled": false,
    "route_mode": "native"
}))]
pub struct NetworkSpec {
    /// Owning tenant identifier.
    #[schema(example = "tenant-0001")]
    pub tenant_id: String,
    /// Human-readable network name.
    #[schema(example = "prod-vpc")]
    pub name: String,
    /// Network mode such as `l2`, `l3`, or `overlay`.
    #[schema(example = "l3")]
    pub network_type: String,
    /// Whether IPv4 addressing is enabled.
    #[schema(example = true)]
    pub ipv4_enabled: bool,
    /// Whether IPv6 addressing is enabled.
    #[schema(example = false)]
    pub ipv6_enabled: bool,
    /// Route execution mode such as `native`, `overlay`, or `hybrid`.
    #[schema(example = "native")]
    pub route_mode: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "phase": "ready"
}))]
pub struct NetworkStatus {
    /// Lifecycle phase as observed by the platform.
    #[schema(example = "ready")]
    pub phase: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "metadata": {
        "id": "network-0001",
        "resource_version": "1",
        "created_at": "1712649600",
        "updated_at": "1712649600",
        "labels": {"tier": "prod"}
    },
    "spec": {
        "tenant_id": "tenant-0001",
        "name": "prod-vpc",
        "network_type": "l3",
        "ipv4_enabled": true,
        "ipv6_enabled": false,
        "route_mode": "native"
    },
    "status": {
        "phase": "ready"
    }
}))]
pub struct NetworkResource {
    pub metadata: ResourceMetadata,
    pub spec: NetworkSpec,
    pub status: NetworkStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct CreateNetworkRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceCreateMetadata>,
    pub spec: NetworkSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct UpdateNetworkRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceUpdateMetadata>,
    pub spec: NetworkSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct NetworkListResponse {
    pub items: Vec<NetworkResource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    pub total_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "tenant_id": "tenant-0001",
    "network_id": "network-0001",
    "segment_id": "segment-0001",
    "instance_id": "instance-0001",
    "node_id": "node-0001",
    "mac_address": "fa:16:3e:11:22:33",
    "fixed_ips": ["10.0.0.10/24"],
    "security_group_ids": ["sg-0001"],
    "allowed_address_pairs": ["10.0.0.20"],
    "anti_spoof_enabled": true,
    "admin_state_up": true
}))]
pub struct PortSpec {
    /// Owning tenant identifier.
    #[schema(example = "tenant-0001")]
    pub tenant_id: String,
    /// Logical network identifier the port belongs to.
    #[schema(example = "network-0001")]
    pub network_id: String,
    /// Optional segment identifier under the network.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "segment-0001")]
    pub segment_id: Option<String>,
    /// Optional bound instance identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "instance-0001")]
    pub instance_id: Option<String>,
    /// Optional hosting node identifier.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "node-0001")]
    pub node_id: Option<String>,
    /// Port MAC address.
    #[schema(example = "fa:16:3e:11:22:33")]
    pub mac_address: String,
    /// Fixed addresses assigned to the port.
    #[serde(default)]
    pub fixed_ips: Vec<String>,
    /// Attached security groups.
    #[serde(default)]
    pub security_group_ids: Vec<String>,
    /// Additional addresses allowed beyond the fixed set.
    #[serde(default)]
    pub allowed_address_pairs: Vec<String>,
    /// Whether anti-spoof protection is enabled.
    #[schema(example = true)]
    pub anti_spoof_enabled: bool,
    /// Administrative up/down state.
    #[schema(example = true)]
    pub admin_state_up: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "phase": "pending",
    "attachment_state": "detached"
}))]
pub struct PortStatus {
    /// Lifecycle phase as observed by the platform.
    #[schema(example = "pending")]
    pub phase: String,
    /// High-level attachment state for the port.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "detached")]
    pub attachment_state: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "metadata": {
        "id": "port-0001",
        "resource_version": "1",
        "created_at": "1712649600",
        "updated_at": "1712649600",
        "labels": {"role": "frontend"}
    },
    "spec": {
        "tenant_id": "tenant-0001",
        "network_id": "network-0001",
        "segment_id": "segment-0001",
        "instance_id": "instance-0001",
        "node_id": "node-0001",
        "mac_address": "fa:16:3e:11:22:33",
        "fixed_ips": ["10.0.0.10/24"],
        "security_group_ids": ["sg-0001"],
        "allowed_address_pairs": ["10.0.0.20"],
        "anti_spoof_enabled": true,
        "admin_state_up": true
    },
    "status": {
        "phase": "pending",
        "attachment_state": "detached"
    }
}))]
pub struct PortResource {
    pub metadata: ResourceMetadata,
    pub spec: PortSpec,
    pub status: PortStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct CreatePortRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceCreateMetadata>,
    pub spec: PortSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct UpdatePortRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceUpdateMetadata>,
    pub spec: PortSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct PortListResponse {
    pub items: Vec<PortResource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    pub total_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "direction": "ingress",
    "ethertype": "ipv4",
    "src_selector": "0.0.0.0/0",
    "dst_selector": "10.0.0.0/24",
    "protocol": "tcp",
    "port_range": "443",
    "action": "allow",
    "priority": 100,
    "log_enabled": false,
    "audit_mode": false
}))]
pub struct SecurityRuleSpec {
    /// Rule direction such as `ingress` or `egress`.
    #[schema(example = "ingress")]
    pub direction: String,
    /// EtherType family such as `ipv4` or `ipv6`.
    #[schema(example = "ipv4")]
    pub ethertype: String,
    /// Optional source selector.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "0.0.0.0/0")]
    pub src_selector: Option<String>,
    /// Optional destination selector.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "10.0.0.0/24")]
    pub dst_selector: Option<String>,
    /// Optional protocol selector.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "tcp")]
    pub protocol: Option<String>,
    /// Optional port range expression.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "443")]
    pub port_range: Option<String>,
    /// Rule action.
    #[schema(example = "allow")]
    pub action: String,
    /// Lower values are evaluated first.
    #[schema(example = 100)]
    pub priority: u32,
    /// Whether matching should emit an explicit policy log.
    #[schema(example = false)]
    pub log_enabled: bool,
    /// Whether the rule runs in audit-only mode.
    #[schema(example = false)]
    pub audit_mode: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "tenant_id": "tenant-0001",
    "name": "frontend",
    "description": "Frontend ingress policy set",
    "rules": [
        {
            "direction": "ingress",
            "ethertype": "ipv4",
            "src_selector": "0.0.0.0/0",
            "dst_selector": "10.0.0.0/24",
            "protocol": "tcp",
            "port_range": "443",
            "action": "allow",
            "priority": 100,
            "log_enabled": false,
            "audit_mode": false
        }
    ]
}))]
pub struct SecurityGroupSpec {
    /// Owning tenant identifier.
    #[schema(example = "tenant-0001")]
    pub tenant_id: String,
    /// Human-readable security group name.
    #[schema(example = "frontend")]
    pub name: String,
    /// Optional description.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "Frontend ingress policy set")]
    pub description: Option<String>,
    /// Ordered security rules.
    #[serde(default)]
    pub rules: Vec<SecurityRuleSpec>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "phase": "ready",
    "rule_count": 1
}))]
pub struct SecurityGroupStatus {
    /// Lifecycle phase as observed by the platform.
    #[schema(example = "ready")]
    pub phase: String,
    /// Materialized rule count.
    #[schema(example = 1)]
    pub rule_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "metadata": {
        "id": "sg-0001",
        "resource_version": "1",
        "created_at": "1712649600",
        "updated_at": "1712649600",
        "labels": {"tier": "frontend"}
    },
    "spec": {
        "tenant_id": "tenant-0001",
        "name": "frontend",
        "description": "Frontend ingress policy set",
        "rules": [
            {
                "direction": "ingress",
                "ethertype": "ipv4",
                "src_selector": "0.0.0.0/0",
                "dst_selector": "10.0.0.0/24",
                "protocol": "tcp",
                "port_range": "443",
                "action": "allow",
                "priority": 100,
                "log_enabled": false,
                "audit_mode": false
            }
        ]
    },
    "status": {
        "phase": "ready",
        "rule_count": 1
    }
}))]
pub struct SecurityGroupResource {
    pub metadata: ResourceMetadata,
    pub spec: SecurityGroupSpec,
    pub status: SecurityGroupStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct CreateSecurityGroupRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceCreateMetadata>,
    pub spec: SecurityGroupSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct UpdateSecurityGroupRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceUpdateMetadata>,
    pub spec: SecurityGroupSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct SecurityGroupListResponse {
    pub items: Vec<SecurityGroupResource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    pub total_count: usize,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "destination": "0.0.0.0/0",
    "next_hop_type": "gateway",
    "next_hop_ref": "gw-0001",
    "preference": 100,
    "scope": "global",
    "status": "active"
}))]
pub struct RouteSpec {
    /// Destination prefix.
    #[schema(example = "0.0.0.0/0")]
    pub destination: String,
    /// Next hop type such as `local`, `node`, `gateway`, or `service`.
    #[schema(example = "gateway")]
    pub next_hop_type: String,
    /// Identifier or opaque reference to the selected next hop.
    #[schema(example = "gw-0001")]
    pub next_hop_ref: String,
    /// Route preference within the table.
    #[schema(example = 100)]
    pub preference: u32,
    /// Optional route scope.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "global")]
    pub scope: Option<String>,
    /// Optional status string for precomputed entries.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "active")]
    pub status: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "network_id": "network-0001",
    "name": "prod-main",
    "routes": [
        {
            "destination": "0.0.0.0/0",
            "next_hop_type": "gateway",
            "next_hop_ref": "gw-0001",
            "preference": 100,
            "scope": "global",
            "status": "active"
        }
    ],
    "default_route": "gw-0001"
}))]
pub struct RouteTableSpec {
    /// Logical network identifier that owns the table.
    #[schema(example = "network-0001")]
    pub network_id: String,
    /// Human-readable route table name.
    #[schema(example = "prod-main")]
    pub name: String,
    /// Statically configured routes.
    #[serde(default)]
    pub routes: Vec<RouteSpec>,
    /// Optional default route reference.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "gw-0001")]
    pub default_route: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "phase": "ready"
}))]
pub struct RouteTableStatus {
    /// Lifecycle phase as observed by the platform.
    #[schema(example = "ready")]
    pub phase: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "metadata": {
        "id": "rt-0001",
        "resource_version": "1",
        "created_at": "1712649600",
        "updated_at": "1712649600",
        "labels": {"scope": "prod"}
    },
    "spec": {
        "network_id": "network-0001",
        "name": "prod-main",
        "routes": [
            {
                "destination": "0.0.0.0/0",
                "next_hop_type": "gateway",
                "next_hop_ref": "gw-0001",
                "preference": 100,
                "scope": "global",
                "status": "active"
            }
        ],
        "default_route": "gw-0001"
    },
    "status": {
        "phase": "ready"
    }
}))]
pub struct RouteTableResource {
    pub metadata: ResourceMetadata,
    pub spec: RouteTableSpec,
    pub status: RouteTableStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct CreateRouteTableRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceCreateMetadata>,
    pub spec: RouteTableSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct UpdateRouteTableRequest {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub metadata: Option<ResourceUpdateMetadata>,
    pub spec: RouteTableSpec,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
pub struct RouteTableListResponse {
    pub items: Vec<RouteTableResource>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
    pub total_count: usize,
}
