use serde::{Deserialize, Serialize};
#[allow(unused_imports)]
use serde_json::json;
use std::collections::BTreeMap;
use utoipa::ToSchema;

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "id": "tenant-0001",
    "resource_version": "3",
    "created_at": "1712649600",
    "updated_at": "1712649655",
    "labels": {
        "env": "prod"
    }
}))]
pub struct ResourceMetadata {
    /// Stable resource identifier.
    #[schema(example = "tenant-0001")]
    pub id: String,
    /// Monotonic resource version used for audit and optimistic workflows.
    #[schema(example = "3")]
    pub resource_version: String,
    /// Creation timestamp string generated by the controller.
    #[schema(example = "1712649600")]
    pub created_at: String,
    /// Last update timestamp string generated by the controller.
    #[schema(example = "1712649655")]
    pub updated_at: String,
    /// Free-form labels attached to the resource.
    #[serde(default)]
    pub labels: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "id": "tenant-0001",
    "labels": {
        "env": "prod"
    }
}))]
pub struct ResourceCreateMetadata {
    /// Optional caller-provided identifier. When omitted the controller allocates one.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "tenant-0001")]
    pub id: Option<String>,
    /// Optional labels to attach on creation.
    #[serde(default)]
    pub labels: BTreeMap<String, String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, ToSchema)]
#[schema(example = json!({
    "resource_version": "3",
    "labels": {
        "env": "staging"
    }
}))]
pub struct ResourceUpdateMetadata {
    /// Optional last-seen resource version supplied by the caller.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    #[schema(example = "3")]
    pub resource_version: Option<String>,
    /// Optional full replacement label set.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub labels: Option<BTreeMap<String, String>>,
}
